export const COMPONENTS = [
  'Accordion',
  'ActionSheet',
  'Alert',
  'AlertDialog',
  'AspectRatio',
  'Avatar',
  'Badge',
  'Button',
  'CalendarView',
  'Card',
  'Checkbox',
  'Collapsible',
  'ContextMenu',
  'DatePicker',
  'Dialog',
  'DropdownMenu',
  'HoverCard',
  'Input',
  'Label',
  'Menubar',
  'Popover',
  'Progress',
  'RadioGroup',
  'Select',
  'Separator',
  'Skeleton',
  'Slider',
  'Switch',
  'Tabs',
  'Text',
  'Textarea',
  'Toast',
  'Toggle',
  'ToggleGroup',
  'Tooltip',
] as const;

export type ComponentName = (typeof COMPONENTS)[number];

